### ISSUE TITLE
passing subscriptionsEndpoint to graphiql breaks it entirely

### ISSUE THREAD

**Issue by micimize** [angel-dart/angel#250]
```
TypeError: this.createMaxConnectTimeGenerator is not a functionclient.js:338:45
    SubscriptionClient http://unpkg.com/subscriptions-transport-ws@0.8.3/browser/client.js:338
    onload http://127.0.0.1:3000/graphiql:37
    (Async: EventHandlerNonNull)
    <anonymous> http://127.0.0.1:3000/graphiql:27
```

Seems like the issue has something to do with `subscriptions-transport-ws@0.8.3` although it still doesn't work with `subscriptions-transport-ws@0.5.4`
